Add Customers Listing Page
tighten/nova-stripe pull request #33
Opened 2021-07-21 13:31 UTC by faxblaster

Adds a simple listing page and navigation item for Customers.  Also includes a minor refactor of pagination to make it easier to use across multiple components. Fixes some formatting with prettier.

<img width="1534" alt="Screen Shot 2021-07-21 at 8 58 49 AM" src="https://user-images.githubusercontent.com/4378273/126495802-2fcb9e39-ae40-49c4-8568-7cacb2eaae0c.png">

2021-07-21 13:34 UTC, faxblaster commented
Leaving in draft until we can merge #30 & #32.

2021-08-18 21:51 UTC, mattstauffer requested changes
Great work! Only one requested change

2021-08-18 21:51 UTC, mattstauffer commented on resources/js/components/CustomersTable.vue
> +            </table>
We might want to add an empty state that just says something like "No customers"

2021-08-18 21:51 UTC, mattstauffer commented on resources/js/components/PaginationLinks.vue
>  <template>
Wow, easy refactor. Nice work!

2021-08-18 22:11 UTC, merged